[tool.ruff]
target-version = "py311"


[tool.ruff.lint]
ignore = ["F403", "E501", "B904"]
exclude = ["*/migrations/*", "*/.venv/*", "*/.env/*"]
select = [
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort
    "C", # flake8-comprehensions
    "B", # flake8-bugbear
    "UP", # pyupgrade
    "Q", # Pyflakes quality
    "S", # Complexity (McCabe)
    "R", # Refactoring
    "T", # Type Annotations
    "DJ", # flake8-django

]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
docstring-code-line-length = "dynamic"
line-ending = "auto"
